language: bash

script:
  - #sudo apt-get install -y hhsuite # Install HH-suite
  - #git clone --recursive https://github.com/soedinglab/CCMpred.git # Install CCMPred
  - #cd CCMpred
  - #cmake .
  - #make
  - #cd ..
  - #sudo apt-get install -y freecontact # Install FreeContact
  - #wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh # Install Conda
  - #bash miniconda.sh -b -p ./miniconda
  - #export PATH="$HOME/build/psipred/DMPfold/miniconda/bin:$PATH"
  - #conda config --set always_yes yes --set changeps1 no
  - #conda config --add channels salilab # Install MODELLER
  - #conda install modeller
  - #sed -i "s/XXXX/$MODELLERKEY/g" miniconda/lib/modeller-9.21/modlib/modeller/config.py
