language: bash

script:
  - sudo apt-get install -y hhsuite
  - git clone --recursive https://github.com/soedinglab/CCMpred.git
  - cd CCMpred
  - cmake .
  - make
  - cd ..
  - sudo apt-get install -y freecontact
  - python -c "import sys; print(sys.version_info)"
  - which conda
  - conda install modeller
