language: bash

script:
  - ./external_bin/psicov # Temp
  - sudo apt-get install -y hhsuite # Install HH-suite
  - git clone --recursive https://github.com/soedinglab/CCMpred.git # Install CCMPred
  - cd CCMpred
  - cmake .
  - make
  - cd ..
  - ls -l CCMPred/bin # Temp
  - sudo apt-get install -y freecontact # Install FreeContact
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh # Install Conda
  - bash miniconda.sh -b -p ./miniconda
  - export PATH="~/build/psipred/DMPfold/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - yes | pip install numpy scipy # Install NumPy and SciPy
  - conda install modeller -c salilab # Install MODELLER
  - sed -i "s/XXXX/$MODELLERKEY/g" miniconda/lib/modeller-9.21/modlib/modeller/config.py
  - conda install pytorch-cpu torchvision-cpu -c pytorch # Install Pytorch
  - python -c "import torch"
  - curl $CNSURL -o cns_solve_1.3.tgz # Install CNS
  - tar -zxvf cns_solve_1.3.tgz
  - sudo apt-get install -y csh # Install csh shell
  - sudo apt-get install -y libgfortran3 # Install libgfortran3
  - ./external_bin/psicov # Temp
  - sudo apt-get install -y libgomp1 # Install libgomp1
  - ./external_bin/psicov # Temp
  - ulimit -s unlimited
  - sed -i "s/set dmpfolddir = ~\/dmpfold/set dmpfolddir = ~\/build\/psipred\/DMPfold/" seq2maps.csh # Modify installed locations
  - sed -i "s/set ccmpreddir = ~\/CCMpred\/bin/set ccmpreddir = ~\/build\/psipred\/CCMpred\/bin/" seq2maps.csh
  - sed -i "s/set freecontactcmd = ~\/freecontact\/bin\/freecontact/set freecontactcmd = freecontact/" seq2maps.csh
  - sed -i "s/dmpfolddir=~\/DMPfold/dmpfolddir=~\/build\/psipred\/DMPfold/" run_dmpfold.sh
  - sed -i "s/source ~\/cns_solve_1.3\/cns_solve_env.sh/source ~\/build\/psipred\/DMPfold\/cns_solve_1.3\/cns_solve_env_sh/" run_dmpfold.sh
  - sed -i "s/\$HHBIN\/hhblits/#\$HHBIN\/hhblits/" seq2maps.csh # For autobuild, eliminate HHblits step and use existing a3m file
  - cp example/PF10963.a3m .
  - csh seq2maps.csh example/PF10963.fasta # Generate map and 21c files
  - du -h PF10963.map PF10963.21c
  - bash run_dmpfold.sh example/PF10963.fasta PF10963.21c PF10963.map ./PF10963 3 5 # Run DMPfold
  - head PF10963/final_1.pdb
  - curl https://zhanglab.ccmb.med.umich.edu/TM-align/TMalign.gz | gunzip > TMalign # Download TMalign
  - chmod +x TMalign
  - ./TMalign PF10963/final_1.pdb example/3FGX.pdb # Check model accuracy
  - tma=$(./TMalign PF10963/final_1.pdb example/3FGX.pdb | grep "if normalized by length of Chain_1" | sed -E 's/^.{10}//' | sed -E 's/.{37}$//')
  - if (( $(echo "$tma >= 0.5" | bc -l) )); then echo "Correct fold, TMalign score $tma"; else echo "Incorrect fold, TMalign score $tma"; exit 1; fi # Throw an error if the model is the wrong fold
